### ISSUE TITLE
S3 integration - CKAN APP

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [AuScope/ckan-docker#100]

**Comment by bmotevalli** [comment]
@kitchenprinzessin3880 I created a separate issue (#104) that relates to my part which is grant permissions to EASI cluster pods to directly access S3 buckets in our AVRE account. We can preserve this issue to @stuartwoodman ends.

**Comment by kitchenprinzessin3880** [comment]
@bmotevalli i ahve added label and project in issue 104

**Comment by kitchenprinzessin3880** [comment]
Anu to test if the data uploaded via UI copied into bucket and then close this issue

**Comment by kitchenprinzessin3880** [comment]
6 minutes max for uploading data (timeout) - we need to check the duration for uploading max limit allowed

**Comment by kitchenprinzessin3880** [comment]
Basic Upload Test - Updated existing record with new file upload, file uploaded saved into S3 bucket
<img width="1007" alt="Screenshot 2024-04-15 at 9 35 28 AM" src="https://github.com/AuScope/ckan-docker/assets/11935313/
<img width="899" alt="Screenshot 2024-04-15 at 9 37 14 AM" src="https://github.com/AuScope/ckan-docker/assets/11935313/4ad70bfc-3550-410d-846f-5ab581039d6b">
47bb2368-675c-4151-8150-3983bfdb100c">

**Comment by kitchenprinzessin3880** [comment]
@stuartwoodman i am going to create a new task for the spinner and max file upload testing, fyi.
