### ISSUE TITLE
502 Bad Gateway only on DEV version of Sample Repostory

### ISSUE THREAD

**Issue by bmotevalli** [AuScope/ckan-docker#112]
AAF login does not properly work on DEV version of Sample Repository. A 502 Bad Gateway is received after the login. If the page is refreshed, then user is successfully logged in.

Possible root cause:

- it probably shouldn't be from AAF set up, as user is being logged in successfully. Though, it might be due to redirect / callback urls. Worth checking that (Ben)
- Check the ckan source code. (Neda)

**Comment by bmotevalli** [comment]
What has been checked/ruled out so far?
-	Locally it is working perfectly fine
-	Sanity checks on all env vars and compare them against all other three instances. In particular, the variables that directly affect log in:
o	CKANEXT_OIDC_PKCE_BASE_URL: https://central.test.aaf.edu.au/
o	CKANEXT__OIDC_PKCE__AUTH_PATH: /oidc/authorize
o	CKANEXT__OIDC_PKCE__TOKEN_PATH: /oidc/token
o	CKANEXT__OIDC_PKCE__USERINFO_PATH: /oidc/userinfo
o	CKAN_SITE_URL: https://sample-dev.data.auscope.org.au/
o	CKANEXT_OIDC_PKCE_CLIENT_ID: (double checked)
o	CKANEXT_OIDC_PKCE_CLIENT_SECRET: (double checked)
-	Double checked AAF and it looks it is hitting the AAF correctly (login events are registered in AAF). Also, double checked the URLs and callback url on AAF and looks all good.
-	Created a whole new AAF record for the DEV instance
-	Checked the pod logs and nothing specific found
-	Rolled back the DEV version to the latest release of PROD and the issue persist
-	Checked if the issue could be from DB as the DB was instantiated a long time ago and the Schema has changed for Sample Repo. To check this, connected the local instance to the DB and there was no issue.
-	Checked Flux set up for the DEV and PROD versions of Sample repo and they are quite consistent.
-	Used port forwarding on the sample service (ckan-igsn) to further isolate if something is wrong to that point or it could be related to our ingress. With port forwarding, there was no issue with the site confirming that the error is probably not originating from the deployed app and rather from ingress
-	On ingress I added the following annotation to increase the timeout:
o	alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=1200, h2.body_size=1024

**Comment by bmotevalli** [comment]
**Fresh installation in cmr-avre-team and using geoanalytics domain**

I did a fresh installation of Helm Chart in cmr-avre-team namespace and tried to use our old "geoanalytics" usl (https://auscope-samples-dev.geoanalytics.group/). I used the same container image we use for sample-dev. Even, I exported the same configMaps and secrets and used that for this installation. I only adjusted the following parameters:
 
CKAN_SITE_URL, CKANEXT_OIDC_PKCE_CLIENT_ID, CKANEXT_OIDC_PKCE_CLIENT_SECRET

**Comment by bmotevalli** [comment]
**Using actual sample-dev url with the fresh installation**

Worked fine

**Comment by bmotevalli** [comment]
Finally worked fine after a fresh helm installation in cmr-avre-ckan-dev

Though, I didn't get what was the issue at the end. Actually, after re-installing the app, I inspected the folders in the pod and found following caching folder in CKAN:
/var/lib/ckan/webassets/.webassets-cache
.  On the 502 error it seemed it had some issues with loading some of the webassets. Anyway, I didn't dig in further since it was taking a lot of time, but thought it could be something to keep in my mind for future reference.

**Comment by bmotevalli** [comment]
To keep a note, I also tried reseting solr index and that did not helped. To reset, you can run following commands:

**ckan -c /etc/ckan/default/production.ini search-index clear**
**ckan -c /etc/ckan/default/production.ini search-index rebuild**

**Comment by bmotevalli** [comment]
issue fixed.

**Comment by NTaherifar** [comment]
This issue happened again with the sample production version. To fix it, I cleared the webassets cache. Here’s what I did: 

1. Get into the CKAN pod:  kubectl exec -it pod-name -- /bin/bash
2. Go to the cache folder: cd /var/lib/ckan/webassets/
3. Delete the cache: rm -rf .webassets-cache
4. Restart CKAN: kubectl delete pod pod-name
