### ISSUE TITLE
Concept of Project required for Sample Repository

### ISSUE THREAD

**Issue by bmotevalli** [AuScope/ckan-docker#113]
In Data Repo, Organization and Group concepts are kind of removed. Only one Organization existed (AuScope) as the publisher. Datasets are the concept defining the contributors and editors when creating a new resource.

However, for sample repository, there is no concept of dataset. Members of a project should be able to login and add their samples under their project. Hence, we at least need a project conecpt.

Check out if we can leverage Organization and Group concepts in CKAN.

Ask Stuart's advice on this.

**Comment by kitchenprinzessin3880** [comment]
NO LONGER RELEVANT
