### ISSUE TITLE
Implement local license management in CKAN

### ISSUE THREAD

**Issue by NTaherifar** [AuScope/ckan-docker#117]
- Add a local licenses.json for custom license options.
- Update CKAN configuration to point to this file.
- Adjust schema settings to use these licenses in dataset forms.

**Comment by kitchenprinzessin3880** [comment]
> "title": "Creative Commons Attribution 4.0",
This should be Creative Commons Attribution 4.0 International

**Comment by kitchenprinzessin3880** [comment]
@NTaherifar how do you want me to test this?

**Comment by NTaherifar** [comment]
@kitchenprinzessin3880, It can be tested by adding a new dataset or updating an existing one, and then checking the license in the preview as well as in the resource section.

**Comment by kitchenprinzessin3880** [comment]
license renders well, thanks
<img width="1103" alt="Screenshot 2024-04-18 at 12 00 33 PM" src="https://github.com/AuScope/ckan-docker/assets/11935313/9f55952a-f4b2-4c65-8d10-15c72aec5233">
