### ISSUE TITLE
Large File Uploads

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [AuScope/ckan-docker#118]
Prvi issue - https://github.com/AuScope/ckan-docker/issues/100

1. 6 minutes max for uploading data (timeout) - we need to check the duration for uploading max limit allowed (300 MB per file
2. Duplicate issue - https://github.com/AuScope/ckan-docker/issues/97 (ensure no 502 error)

Test required
1. Can upload file < 300MB, check its duration
2. Cannot upload file > 300MB, error message should be displayed

**Comment by kitchenprinzessin3880** [comment]
@stuartwoodman I can upload 1.24 GB file  e.g. https://repository-dev.data.auscope.org.au/dataset/kimba-airborne-electromagnetic-aem-survey (see synology_updates.zip). I though max size per file is 300MB?

**Comment by stuartwoodman** [comment]
> @stuartwoodman I can upload 1.24 GB file e.g. https://repository-dev.data.auscope.org.au/dataset/kimba-airborne-electromagnetic-aem-survey (see synology_updates.zip). I thought max size per file is 300MB?

That's what it should be, I double checked the setting in the Vault for the dev repo:

![image](https://github.com/AuScope/ckan-docker/assets/15720448/fb1a4e79-1291-4fa4-a228-e76642350029)

**Comment by kitchenprinzessin3880** [comment]
@stuartwoodman can you please check the max limit settings? i can upload the file > 300MB e.g. https://repository-dev.data.auscope.org.au/dataset/kimba-airborne-electromagnetic-aem-survey/resource/478e2704-cb66-493c-89af-940f0ebd3d38

**Comment by kitchenprinzessin3880** [comment]
related discussion - https://teams.microsoft.com/l/message/19:ec392205eadc4703868774a089284470@thread.tacv2/1713404908507?tenantId=0fe05593-19ac-4f98-adbf-0375fce7f160&groupId=e1545fd3-9cb0-4bfa-a927-57ba8abeb0dc&parentMessageId=1713404908507&teamName=AuScope%20AVRE&channelName=Auscope%20Data%20Repository&createdTime=1713404908507

can you please change "The maximum upload size per file is 300MB. If you have larger file(s), please contact us via the Contact Form. We will assist you with data migration." to  "If you have large data e.g. > 10GB, please contact us via the Contact Form. We will assist you with data migration."

**Comment by kitchenprinzessin3880** [comment]
Message has been updated
<img width="683" alt="Screenshot 2024-05-10 at 3 28 46 PM" src="https://github.com/AuScope/ckan-docker/assets/11935313/e377e224-781d-49d6-8dd1-952d97197f42">
