### ISSUE TITLE
User emails are case SENSITIVE

### ISSUE THREAD

**Issue by bmotevalli** [AuScope/ckan-docker#129]
When logging in with AAF, user's email are saved with Upper case. Meanwhile, when inviting a user to a group or organization, if you define the user as a new user and pass in the email address in lower case, a new user with basically same email is created! (in DB there are two users, one with Lower and the other with Upper case). However, if you try to pass in upper cased email, CKAN throws an error mentioning that user already exists!

**Comment by kitchenprinzessin3880** [comment]
pending - updating existing records in the database (dev, prod)

**Comment by bmotevalli** [comment]
@kitchenprinzessin3880 all is done from my end:

- a block of code is added to enforce email lower case
- databases are updated

The dev instance already has this block of code. For PROD, once a new version is released it will be in effect.
