### ISSUE TITLE
Bulk uploads validation

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [AuScope/ckan-docker#160]
Here is the list of validations that should be implemented as part of the bulk uploads

1. Required fields - sample_number, description, user_keywords, sample_type, material_type, author_name, author_name_type, author affiliation, author email, 
2. Conditional required fields
2a. if point_latitude and point longitude is specified, then epsg is required
2b. if author_affiliation_identifier is specified, then author_affiliation_identifier_type is required
2c. if author_identifier is specified, then author_identifier_type is required
2d. if a related resource provided, then all these fields are required related_resource_type, related_resource_url, related_resource_title, relation_type
2e. if a funder is provided,  at least funder_name should be included. if a funder_identifier is specified, then funder_identifier_type is required
2f. if a funder_name is specified, then project fields (project_name, project_identifier, and project_identifier_type) must be specified.

2. controlled terms (must match the value in the template; see cv tab) - sample_type, material_type, epsg_code, author_name_type, author_affiliation_identifier_type, author_identifier_type, related_resource_type, relation_type,funder_identifier_type, project_identifier_type

4. sample_number column values contain no duplicate within the template uploaded
5. The value specified in the parent_sample column must exist in the sample_number column or the same collection
6. these fields, if specified, must be of type number - point_latitude, point_longitude, elevation
7. ensure these fields follow URL format - related_resource_url, author_affiliation_identifier, author_identtifier
8. ensure that a collection is selected before uploading the template

please note that 

1. there are **fields with default values** that you should insert as part of uploading the process (these values will be not specified in the template as they represent the fixed values):
2. parent_sample - these should be represented as a related_resource:

- related_resource_type - PhysicalObject
- related_resource_url, related_resource_title
[1]  if the parent sample is from existing collection, then use the full doi and title of the parent sample for the fields above
[2] if the parent sample is not yet registered with repository but included in the upload file, then you must register first the parent sample, then follow [1].
- relation_type - IsDerivedFrom

**Comment by NTaherifar** [comment]
@kitchenprinzessin3880  

Regarding adding the DOI of the parent sample as related_resource_url, we currently only have the DOI number, not the full DOI URL.

**Comment by kitchenprinzessin3880** [comment]
this should the standard prefix of doi (prod) - https://doi.org/..

**Comment by kitchenprinzessin3880** [comment]
Additional validation required

1. depth_from (if specified) < depth_to
2. acquisition date 1. acquisition_start_date <= acquisition_end_date 2. if parent sample is specified, then validate the dates against the parent sample
3. elevation - must be number
4. sample_repository_contact_name, sample_repository_contact_email

**Comment by kitchenprinzessin3880** [comment]
i am going to close this issue. pending and new validation tasks are reported here https://github.com/AuScope/ckan-docker/issues/265
