### ISSUE TITLE
An elevation value cannot be entered into form 

### ISSUE THREAD

**Issue by vjf** [AuScope/ckan-docker#162]
How to reproduce:
- Login via AAF, click on "Datasets"
- Try to create a new data set, click on  "Add Dataset"
- Enter in values for all the mandatory fields
- Under "Spatial and Temporal":
    - select "Single point on Map"
    - click on a point on map
- Enter in "10" in the "Elevation" text box
- Press "Next: Add Data" button

There will be a red error box at the top of the form:

> The form contains invalid entries:
> 
> vertical_datum: Missing value

**Comment by kitchenprinzessin3880** [comment]
elevation can be added
