### ISSUE TITLE
Login failed. Bad username or password. 

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [AuScope/ckan-docker#168]
I can login into https://repository-dev.data.auscope.org.au as ckan_admin, but it display the error below. When I refresh the page, the error disappears.
<img width="1352" alt="Screenshot 2024-05-10 at 3 06 18 PM" src="https://github.com/AuScope/ckan-docker/assets/11935313/c001c36a-3954-4fe4-a6b9-d0bdd3b9292b">

**Comment by stuartwoodman** [comment]
I think this may be the issue I mentioned last meeting. If it is, what happens is if the user enters an incorrect username or password they are prompted to try again but the error message does not display. If they log in correctly then the error message they should have got the screen before finally displays, which is very confusing.

**Comment by stuartwoodman** [comment]
Pull request for this and elevation issue:
https://github.com/AuScope/ckan-docker/pull/181

**Comment by kitchenprinzessin3880** [comment]
error message is no longer displayed after incorrect login > correct login
