### ISSUE TITLE
Add repository citation guideline

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [AuScope/ckan-docker#170]
Citation recommendation – develop one for AuScope data repository (see example https://auspass.edu.au/about.html) Action: Anu & Lesley & Stuart 
i.	Related paper - https://www.nature.com/articles/s41597-023-02491-7 
ii.	Example of auscope data - https://academic.oup.com/gji/article/237/2/849/7616930?login=false#444092587

**Comment by NTaherifar** [comment]
@kitchenprinzessin3880, is there something I need to do here?

**Comment by kitchenprinzessin3880** [comment]
Not yet. once i created the document, you just need to link it under the menu Help.

**Comment by kitchenprinzessin3880** [comment]
Final doc - https://csiroau.sharepoint.com/:w:/r/sites/AuScopePortalRefresh/Shared%20Documents/General/auscope_data_repository/publications/Referencing_Citing_AuScopeRepository.docx?d=we2d6e4a099c74351b93e3a3a18ae001b&csf=1&web=1&e=m9DoGb

**Comment by kitchenprinzessin3880** [comment]
adde by @NTaherifar see  https://repository-dev.data.auscope.org.au/citation-guide
