### ISSUE TITLE
Include Request Types in subject field of the contact form

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [AuScope/ckan-docker#192]
Please include the following request types in the subject field and place the field on the top

Data Repository

- General/Other Enquiry
- Large Data Upload
- Data Updates
- Data Access

Sample Repository

- General/Other Enquiry
- Bulk Sample Upload
- Collection/Samples Updates
- Collection Creation/Access

**Comment by NTaherifar** [comment]
After merging into the master branch, the variable CKAN__PLUGINS should be updated so that the contact plugin is placed after the auscope plugin. This ensures that the auscope plugin can inherit from the contact plugin and apply our custom changes.

**Comment by kitchenprinzessin3880** [comment]
Request types has been added into the contact form
![Screenshot 2024-05-29 at 12 00 59 PM](https://github.com/AuScope/ckan-docker/assets/11935313/4392c11c-d945-4a7f-975d-d64da396181c)
details sent via the form received via the email, see below
<img width="702" alt="Screenshot 2024-05-29 at 12 03 01 PM" src="https://github.com/AuScope/ckan-docker/assets/11935313/d5bff983-a9b6-4409-85a0-01e9eec9200d">
