### ISSUE TITLE
Allow all users to see private datasets (but not access unless authorized).

### ISSUE THREAD

**Issue by stuartwoodman** [AuScope/ckan-docker#194]
This already happens for users who are not logged in on the front page, but not the Datasets screen.
For members this does not happen on the home screen or Datasets (see below).

For members, they do not see private datasets because of this line in schema.py's after_dataset_search function:

if user_role == 'member' and package['private'] and user.id != package['creator_user_id']:
    filtered_results.remove(package)

An anonymous user won't have a role, hence no packages will be removed. Although anonymous user's won't see anything in Datasets, either, so perhaps the front screen is using different code.

**Comment by stuartwoodman** [comment]
Pull request:
https://github.com/AuScope/ckan-docker/pull/196

**Comment by kitchenprinzessin3880** [comment]
tests performed at https://repository-dev.data.auscope.org.au/

1. no login and can view private datasets headings on the main page - PASS
2. login as a member and can view private datasets headings on the main page - PASS
3. no login > click on Datasets, can see private datasets headings only - PASS
4. login as a member > click on Datasets, can see private datasets headings only - PASS
5. login as ckan admin, can view private datasets from the main page and by clicking the Dataset link - PASS
