### ISSUE TITLE
Organization does not exist

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [AuScope/ckan-docker#212]
1. Help text contain incorrect url form - Author Identifier field (THIS HAS BEEN RESOLVED BY @NTaherifar , anu to test)

Uniquely identifies an individual or legal entity, according to identifier schemes. Please specify the absolute URL, e.g. `https://://o`rcid.org/0000-0003-0870-3192 
Please find the URL

1. organization not found although i can search it via the drop down menu
<img width="551" alt="Screenshot 2024-06-07 at 5 34 25 PM" src="https://github.com/AuScope/ckan-docker/assets/11935313/9aa233a0-a708-478e-a576-cf7e4fa3466d">

**Comment by kitchenprinzessin3880** [comment]
Response from @NTaherifar via email:

I think if we delete the "auscope" organization from production and then refresh the website and log in with the admin role, everything will be okay. However, I recommend waiting for Stu to see what he suggests.
Cheers,
Neda
 
From: Taherifar, Neda (Mineral Resources, Kensington WA)
Sent: Monday, June 10, 2024 9:56 AM
To: Devaraju, Anusuriya (Mineral Resources, Kensington WA) <[Anusuriya.Devaraju@csiro.au](mailto:Anusuriya.Devaraju@csiro.au)>
Cc: Woodman, Stuart (Mineral Resources, Clayton) <[Stuart.Woodman@csiro.au](mailto:Stuart.Woodman@csiro.au)>
Subject: RE: Prod Repository - Important
 
Hi Anu,
In the code, by default, the organization "auscope" with the ID "12345678-1234-1234-1234-123456789012" will be added to the database. Later, this ID will be used as the "owner_org" to submit datasets.

In the development version, you can see that the "auscope" organization is set up correctly (see Development Organization). However, in production, the ID of "auscope" is not as expected (see [Production Organization](https://repository.data.auscope.org.au/api/3/action/organization_show?id=auscope)).

Since the "owner_org" ID is hardcoded, during submission, the "owner_org" is set to "12345678-1234-1234-1234-123456789012", but this ID does not exist in the production database. I suspect that the "auscope" organization was added to the database before the new modification, which is causing this mismatch.

This is my understanding; however, Stu is very familiar with this part and can confirm if it is correct or not.

Cheers,
Neda

**Comment by kitchenprinzessin3880** [comment]
@stuartwoodman can you please add 1-2 sentences on how you fix the issue and the close it?

**Comment by stuartwoodman** [comment]
The org_visibility organisation validator for the owner_org field was using the hard-coded ID of the organisation, which wasn't present in production as the organisation has been manually entered, not created with the start-up script. The validator now uses the organisation name (auscope) to retrieve the organisation rather than the ID.
