### ISSUE TITLE
SMTP User Creds Automatic Rotation

### ISSUE THREAD

**Issue by bmotevalli** [AuScope/ckan-docker#219]
Add automatic rotation of SMTP User Creds.

**Comment by kitchenprinzessin3880** [comment]
[12/06 13:26] Bradley, Sam (Mineral Resources, Kensington WA)
Apparently there is a special conversion to go from an aws secret to a n SMTP password but AWS only decides to do that for you when you first create the user and not when you regenerate the keys

**Comment by bmotevalli** [comment]
@kitchenprinzessin3880 @SamuelBradley @stuartwoodman 

This is completed with following comments:

- The IAM secret key required a conversion. For reference, following doc worked for me to do the conversion: https://repost.aws/knowledge-center/ses-rotate-smtp-access-keys
- A task is added to rotate the SMTP creds every 30 days. You can adjust the time interval in the manifest that defines the creds rotation. The manifest is located here: https://dev.azure.com/CSIROMineralResources/AuScope%20AVRE/_git/avre-kube-watch?path=/easi/cmr-avre-ckan-prod/rotate_aws_iam_cred_data_repo.yaml
- IMPORTANT NOTE: DEV and PROD are using the same SMPT credentials. Hence, the creds had to be updated in both environments. We couldn't run the same job in both environments as they would attempt to rotate the same creds simultaneously. To tackle this problem, I run the job in the PROD environment, but I update the creds in Vault paths of both environments. For the PROD instance, the pods immediately restarts as they are all a part of same CronJob. But for DEV, the changes will probably be into affect in the next round of CronJob, once it tries to sync with the new secrets.
