### ISSUE TITLE
Design and Styling

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [AuScope/ckan-docker#252]
Ref: https://sample.data.auscope.org.au/

1. Quick Start - replace text (4.) with the following: Select your [collection](https://sample.data.auscope.org.au/organization/) and choose

- Add Sample (register individual samples via the online form)
- Batch Upload Sample (register multiple samples by uploading a spreadsheet) *please link 'spreadsheet' with https://sample.data.auscope.org.au/path/to/preformatted_template.xlsx 

2. Submit a request (hyperlink is not visible)...

**Comment by NTaherifar** [comment]
@kitchenprinzessin3880 , The issue is resolved and can be tested in the development version.

**Comment by kitchenprinzessin3880** [comment]
quick start updated
<img width="654" alt="Screenshot 2024-07-29 at 3 04 58 PM" src="https://github.com/user-attachments/assets/f79709db-01a5-4f82-8436-435013b2d590">
