### ISSUE TITLE
About section of the igsn repository

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [AuScope/ckan-docker#253]
https://sample.data.auscope.org.au/about

This should be revised to reflect the scope of the sample repository, e.g. purpose, why the catalogue is important.
also avoid the term sample data, instead use sample metadata/catalogue..

**Comment by PavelGolodoniuc** [comment]
@NTaherifar, please use the following text for the About page:

> The AuScope Virtual Research Environment (AVRE) is an AuScope program that focuses on delivering data, services, and tools to support the future research of the Australian geoscience research community. AVRE provides a rich ecosystem of Findable, Accessible, Interoperable and Reusable (FAIR) data and tools to a diverse range of Australian research organisations, government geological surveys and the international community. The AVRE program has contributed to the development and spearheaded the adoption of the International Generic Sample Numbers (IGSN) system in Australia in collaboration with the IGSN e.V. Organisation, DataCite, and the Australian Research Data Commons (ARDC).
> 
> The AuScope Sample Repository aims to offer a digital repository for the AuScope community to register persistent identifiers for specimen data and publish specimen metadata following the [FAIR Data Guiding Principles](https://www.go-fair.org/fair-principles/). The AuScope communities comprise NCRIS-funded data projects and Australian geoscience research communities. The AuScope Sample Repository is operated as a self-service facility for the storage, dissemination, and publication of metadata from AuScope-funded projects and instruments.

**Comment by NTaherifar** [comment]
@PavelGolodoniuc @kitchenprinzessin3880 

Both the production and development versions have been deployed and are ready for review.

**Comment by kitchenprinzessin3880** [comment]
@NTaherifar
"persistent identifiers for specimen data and "...please remove the term 'data'
"he AuScope Sample Repository aims to offer a digital repository for the AuScope community" -> replace community with communities

**Comment by NTaherifar** [comment]
@kitchenprinzessin3880 
The changes are applied and ready to review on both dev and prod.

**Comment by kitchenprinzessin3880** [comment]
the about section has been updated (tested https://sample-dev.data.auscope.org.au/about)
