### ISSUE TITLE
incorrect admin email

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [AuScope/ckan-docker#255]
There are several places the email included is old email

- https://sample.data.auscope.org.au/user/edit/ckan_admin (sample repository only)
- Dont have AAF? 
-- the mailto title should be AuScope Sample Repository, not AuScope Data Repository
-- the email is incorrect (auscope.doi@csiro.au) at both **data and sample repositories**

**Comment by NTaherifar** [comment]
@kitchenprinzessin3880 , what should the email be? Do I also need to update the data repository?

**Comment by bmotevalli** [comment]
@NTaherifar I already have fixed this. Set the email to: admin@data.auscope.org.au. And we are now receiving the emails in AWS Workmail.

@kitchenprinzessin3880 please give it a test and please inform us if there is an issue.

**Comment by kitchenprinzessin3880** [comment]
@bmotevalli the admin email (both dev and prod) still uses the old email. we need to update the vault entry?
<img width="1137" alt="Screenshot 2024-07-16 at 7 02 49 PM" src="https://github.com/user-attachments/assets/11eb756a-1139-4454-9740-3c13f18c449e">

**Comment by bmotevalli** [comment]
@kitchenprinzessin3880 I already have updated the ENV VARS in vault. The emails are now being received in AWS Workmail. If you see it yet in the admin profile, this then means this field needs to also be updated from UI. Anyway, I tried to login with admin account but I was not able. I assume you have changed the password. Where can we get the new password from?

**Comment by kitchenprinzessin3880** [comment]
all the password in vault (will send the link via teams)

**Comment by NTaherifar** [comment]
@kitchenprinzessin3880 , The issue is resolved and can be tested in the development version.

**Comment by kitchenprinzessin3880** [comment]
Tested email at

1. request new account (pass)
<img width="418" alt="Screenshot 2024-07-29 at 2 58 28 PM" src="https://github.com/user-attachments/assets/5b1c5733-84d7-46c2-a834-ac80be36a665">

2. admin profile (pass)
<img width="405" alt="Screenshot 2024-07-29 at 2 59 10 PM" src="https://github.com/user-attachments/assets/57a52ba0-019b-412a-81fd-9ddc0466ae4d">

3. invite user

4. request collection creation (pass)
