### ISSUE TITLE
Sample collection management

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [AuScope/ckan-docker#258]
1. https://sample.data.auscope.org.au/organization/request_new_collection

- what is related dataset title, URL?
- Is culturally sensitive? use dropdown menu. this requires better definition (SEE BELOW*)
- Submit the request, no email received (both senders and repository admin)

2. Curator role spelling - incorrect?
https://sample-dev.data.auscope.org.au/organization/

<img width="1273" alt="Screenshot 2024-07-16 at 12 22 13 PM" src="https://github.com/user-attachments/assets/8f7d1293-0870-4aae-9e01-f825ab00b238">

**please remove the existing question and replace it with the following:

In Australia, 'Indigenous Data' refers to information or knowledge, in any format or medium, which is
about and may affect Indigenous peoples both collectively and individually [1]. 
Does this collection relate to Indigenous people and impact Indigenous lives at the collective and/or individual level?

- Yes
- No
- Unsure

[1] Maiam nayri Wingara. (2018) Indigenous Data Sovereignty Communique Indigenous Data Sovereignty Summit 20th June 2018, Canberra, ACT. https://static1.squarespace.com/static/5b3043afb40b9d20411f3512/t/63ed934fe861fa061ebb9202/1676514134724/Communique-Indigenous-Data-Sovereignty-Summit.pdf

The font reference [1] should be smaller

**Comment by NTaherifar** [comment]
@kitchenprinzessin3880 , The issue is resolved and can be tested in the development version.

**Comment by kitchenprinzessin3880** [comment]
@NTaherifar the reference should be smaller than main text
<img width="1167" alt="Screenshot 2024-07-29 at 2 55 33 PM" src="https://github.com/user-attachments/assets/a1bc45a2-5fd1-4668-8a3e-cb4ead1e140a">

**Comment by kitchenprinzessin3880** [comment]
Issues on misspelling curator - has been fixed.

**Comment by NTaherifar** [comment]
@kitchenprinzessin3880 , It is completed and ready for testing on both the dev and prod.

**Comment by kitchenprinzessin3880** [comment]
Tested with dev (PASS)

<img width="1177" alt="Screenshot 2024-08-06 at 2 41 46 PM" src="https://github.com/user-attachments/assets/bcbf4358-8fa6-4695-9639-56b75584a5d2">
