### ISSUE TITLE
Cannot join existing collection

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [AuScope/ckan-docker#259]
Cannot join existing collection (https://sample.data.auscope.org.au/organization/request_join_collection?org_id=7b5221d8-fe90-44a1-aab0-e12cc6c2fa9c&org_name=mriwa557)
no email received (both sender and receiver)

**Comment by bmotevalli** [comment]
@kitchenprinzessin3880 this should already be fixed. Please re-test.

**Comment by kitchenprinzessin3880** [comment]
notifications received

<img width="887" alt="Screenshot 2024-07-29 at 3 11 03 PM" src="https://github.com/user-attachments/assets/35726e0e-dfb7-45d1-8331-0566a375a27f">
<img width="686" alt="Screenshot 2024-07-29 at 3 10 55 PM" src="https://github.com/user-attachments/assets/6f0c096e-6d04-4807-abf9-1d9434b7f4d4">
