### ISSUE TITLE
Sample metadata schema

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [AuScope/ckan-docker#262]
1. update definition of **Parent Sample**: "The source sample from which the sample is created or sub-sampled. Select the parent sample from existing samples." PASS
2. place sample_type field after resource type PASS
3. the following fields should be under Spatial & Temporal tab - acquisition_start_date,acquisition_end_date,method, depth_to, depth_from. Follow the order of the fields here PASS
4. Sample Repository Contact Email - incorrect (PASS now takes the collection main contact)
5. sample depth validation - depth_from from should be less than depth_to (this will be addressed by the issue https://github.com/AuScope/ckan-docker/issues/267
6. elevation should be number type **PASS**
7. update definition of author_identifier -  Uniquely identifies an individual or legal entity, according to identifier schemes. Please specify the absolute URL, e.g. https://orcid.org/0000-0003-0870-3192

![Uploading Screenshot 2024-07-29 at 2.47.07 PM.png…]()

**Comment by NTaherifar** [comment]
@kitchenprinzessin3880 , The issue is resolved and can be tested in the development version.

**Comment by kitchenprinzessin3880** [comment]
@NTaherifar elevation should be number

<img width="1017" alt="Screenshot 2024-07-29 at 2 49 01 PM" src="https://github.com/user-attachments/assets/4aa22acb-ba48-4077-9364-0e3e751c3be4">

**Comment by NTaherifar** [comment]
@kitchenprinzessin3880 I have just checked it and noticed that it works correctly in Google Chrome, but there is a problem with Firefox. I will fix it.

**Comment by NTaherifar** [comment]
@kitchenprinzessin3880 , It is completed and ready for testing on both the dev and prod.
