### ISSUE TITLE
Sample sort

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [AuScope/ckan-docker#263]
https://sample-dev.data.auscope.org.au/dataset/
Allow users to sort by table column alphabetically e.g. Sample, Collection

**Comment by NTaherifar** [comment]
@kitchenprinzessin3880 , The issue is resolved and can be tested in the development version.

**Comment by kitchenprinzessin3880** [comment]
sorting has been implemented
![Uploading Screenshot 2024-07-29 at 2.45.47 PM.png…]()
