### ISSUE TITLE
Bulk Template

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [AuScope/ckan-docker#264]
1. rename the button Batch Upload Samples to Start Batch Upload
2. Make the latest version of the template available on the repository; see https://csiroau.sharepoint.com/:f:/r/sites/AuScopePortalRefresh/Shared%20Documents/General/IGSN%20Repository/metadata/upload-template?csf=1&web=1&e=t15U6l

**Comment by NTaherifar** [comment]
@kitchenprinzessin3880 , The issue is resolved and can be tested in the development version.

**Comment by kitchenprinzessin3880** [comment]
<img width="947" alt="Screenshot 2024-07-29 at 2 41 34 PM" src="https://github.com/user-attachments/assets/54cd08a4-f775-41e1-9a05-0a1d0297bf05">
<img width="1098" alt="Screenshot 2024-07-29 at 2 42 36 PM" src="https://github.com/user-attachments/assets/abed1340-0cdb-47f8-8a2e-0efb600226e1">

Button name has been updated. Template can be downloaded and opened.
