### ISSUE TITLE
Schema validation

### ISSUE THREAD

**Issue by NTaherifar** [AuScope/ckan-docker#267]
Ensure that the URL and email fields follow the correct format.

For depth fields:

depth_from (if specified) must be less than depth_to.
For sample dates:

If a parent sample is specified, validate the dates against the parent sample's dates. Specifically, the start date of the sample must be either the same as or later than the start date of its parent sample (i.e., the sample cannot exist before the parent sample).

**Comment by NTaherifar** [comment]
@kitchenprinzessin3880 , The issue is resolved and can be tested in the development version.

**Comment by kitchenprinzessin3880** [comment]
**Test 1** PASS, a small modification required
Depth test - https://sample-dev.data.auscope.org.au/dataset/edit/moolart-soil-sample-mw-2 


<img width="933" alt="Screenshot 2024-07-29 at 2 34 26 PM" src="https://github.com/user-attachments/assets/2e041c94-756f-4bd7-b4b2-17bdb6803909">

**Test 2** PASS
Parent sample - https://sample-dev.data.auscope.org.au/dataset/moolart-surface_soil-sample-mw (1st June - 30th June 2024)
Child sample - https://sample-de
<img width="1187" alt="Screenshot 2024-07-29 at 2 37 50 PM" src="https://github.com/user-attachments/assets/20281dd2-beeb-4d2b-b7a2-df9fcc632438">
v.data.auscope.org.au/dataset/moolart-surface_soil-sample-mw-1

**Comment by kitchenprinzessin3880** [comment]
@NTaherifar if I enter the same depth, the edit is successful. depth_from < depth_to (not <=)

**Comment by NTaherifar** [comment]
@kitchenprinzessin3880 , It is completed and ready for testing on both the dev and prod.

**Comment by kitchenprinzessin3880** [comment]
<img width="750" alt="Screenshot 2024-08-06 at 2 43 02 PM" src="https://github.com/user-attachments/assets/14884e28-bec9-4689-910b-bd554f447a4c">
