### ISSUE TITLE
Delete collection 

### ISSUE THREAD

**Issue by NTaherifar** [AuScope/ckan-docker#268]
Check collection for no members before deleting 
Send email notification after deletion

**Comment by NTaherifar** [comment]
@kitchenprinzessin3880 , It is completed and ready for testing on both the dev and prod.

**Comment by kitchenprinzessin3880** [comment]
<img width="920" alt="Screenshot 2024-08-06 at 2 40 49 PM" src="https://github.com/user-attachments/assets/207892f3-eaa6-4cad-b187-3429a39b5eac">
