### ISSUE TITLE
Child samples are not clickable

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [AuScope/ckan-docker#269]
Tested DEV instance

<img width="475" alt="Screenshot 2024-07-29 at 2 37 12 PM" src="https://github.com/user-attachments/assets/fd346db7-a418-4e18-a614-2fa16c2d4938">

I cannot click on the child sample on the left menu - i need to right click and open in new browser tab.

**Comment by NTaherifar** [comment]
@kitchenprinzessin3880 : To access child samples, please double-click. A single click is used to expand or collapse the tree view.

**Comment by NTaherifar** [comment]
@kitchenprinzessin3880 , It is completed and ready for testing on both the dev and prod.

**Comment by kitchenprinzessin3880** [comment]
tested with dev, double click is working
