### ISSUE TITLE
Format metadata display

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [AuScope/ckan-docker#38]
Dataset example - https://auscope-data-dev.geoanalytics.group/dataset/dataset-created-as-admin
The following changes are required

1. Remove Organization info on the left window, see 'AuScope is Australia's provider of research infrastructure to the national geoscience community w....' (DONE)
2. Add 'Cite this as' followed by a citation under the title (**Citation in complete**)
3. Format Authors (use bullet list for multiple authors) - need your suggestion here to enable better formatting of author information (if user specifies ORCID as Author Identifier Type, then this should translated into hyperlink) (DONE)
5. GCMD Science Keywords - should be clickable links (DONE)
6. Fields of Research - should be an actual field name, not code (DONE)
7. Fields of Research Code (hide this) (DONE)
8. Geographic Coordinate System - should display EPSG name, not code (DONE - both code and name included)
9. Funding Reference - should be hyperlink (DONE)
10. Related Resource - need your suggestion here to enable better formatting ; and ensure the related resource URL is hyperlink (DONE)
11. Publisher, Publisher Identifier, Publisher Identifier Type - should be in one row (and URL should hyperlink) DONE
12. Primary Contact Email - incorrect value (should be auscope data email auscope.doi@csiro.au) DONE
13. Citation (move to the top of the page, see comment 2 above) DONE

<img width="1253" alt="Screenshot 2024-03-06 at 11 07 01 am" src="https://github.com/AuScope/ckan-docker/assets/11935313/faf1c0d9-00dd-475d-9c56-f4641eaf84a0">
<img width="962" alt="Screenshot 2024-03-06 at 11 13 10 am" src="https://github.com/AuScope/ckan-docker/assets/11935313/761f87de-88ed-4224-85fd-8906910af82a">

**Comment by NTaherifar** [comment]
8- Funding Reference, Which field should be displayed as a hyperlink? @kitchenprinzessin3880

**Comment by kitchenprinzessin3880** [comment]
it should be funding identifier

**Comment by kitchenprinzessin3880** [comment]
@NTaherifar @stuartwoodman the citation included on the metadata page is incomplete and the wrong formatting.
e.g. https://repository-dev.data.auscope.org.au/dataset/soil-gas-for-mineral-exploration-field-locations
is this related to UI or backend?

**Comment by kitchenprinzessin3880** [comment]
I am closing this issue as the issue on citation will be addressed here https://github.com/AuScope/ckan-docker/issues/19
