### ISSUE TITLE
GCMD Science Keywords

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [AuScope/ckan-docker#40]
Test instance - auscope-data-dev.geoanalytics.group

Not all keywords populated in the dropdown menu; please make the dropdown menu searchable as the list is very long

**Comment by NTaherifar** [comment]
I made a change in the schema, adding two fields for gcmd_keywords: EPSG_code for the code and gcmd_keywords_code for the descriptive text. The code will not be displayed to the user.

**Comment by kitchenprinzessin3880** [comment]
tested with random gcmd keywords from RVA, can be found on dropdown menu
