### ISSUE TITLE
File upload too large

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [AuScope/ckan-docker#47]
Test instance - auscope-data-dev.geoanalytics.group

@stuartwoodman what is the maximum size of file can be uploaded into CKAN, for our repository? I am getting the following error when uploaded file ~ 24MB
<img width="476" alt="Screenshot 2024-03-06 at 4 16 13 pm" src="https://github.com/AuScope/ckan-docker/assets/11935313/89d8f7c2-c397-4d73-9dcb-43ce2ac6368d">

It seems like CKAN has an upload size limit of 10MB for resources by default. You can raise that in your ini with ckan.max_resource_size = XX, for example ckan.max_resource_size = 100 (which means = 100MB).
Can you please raise it to 100MB?

@NTaherifar we need to add the info below under the File (see Figure Below). 
The maximum upload size per file is 100MB. If you have larger file(s), please contact us via the Contact Form. We will assist you with data migration.

<img width="1004" alt="Screenshot 2024-03-06 at 4 32 42 pm" src="https://github.com/AuScope/ckan-docker/assets/11935313/0135b355-481b-46de-a9e7-b9d9eac77e5b">

**Comment by stuartwoodman** [comment]
I've changed the setting CKAN_MAX_RESOURCE_SIZE to 100 in the Vault for both dev and prod, but these won't get picked up until re-deployment. Will task leave open to make UI changes.

**Comment by kitchenprinzessin3880** [comment]
tested file upload < 100MB (pass), > 100MB (received error message as expected, pass)
