### ISSUE TITLE
Format More Information (of data files)

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [AuScope/ckan-docker#50]
Test instance - auscope-data-dev.geoanalytics.group
Click a dataset, select Explore > More Information (see below)

Actions:

1. The sections highlighted in the figure below should be formatted following - Authors (PublicationYear): File Name (from Title). Publisher.  File URL

Anusuriya Devaraju, Steve Barnes (2024): wa geology layers (from Private Geological Layers of WA)). AuScope. https://auscope-data-dev.geoanalytics.group/dataset/dataset-created-as-admin/resource/4bac4531-1d79-4abf-a290-f26e9d1496f1

3. License (left panel) - should populate the license selected by the user for the dataset
<img width="1162" alt="Screenshot 2024-03-06 at 4 59 30 pm" src="https://github.com/AuScope/ckan-docker/assets/11935313/f088033a-f08a-43ba-b5d9-a4dc7f538bab">

**Comment by NTaherifar** [comment]
@kitchenprinzessin3880 
The license section is intended to show both the license_url and license_title. However, it seems we currently only have a single text field for the license, containing text as 'CC BY 4.0 International'. Would you like me to update the template to display just the license text, 'CC BY 4.0 International', as it is?"

**Comment by kitchenprinzessin3880** [comment]
@NTaherifar  please use url and title, here is the URL - https://creativecommons.org/licenses/by/4.0/
i will update the schema

**Comment by kitchenprinzessin3880** [comment]
Anu to update the schema to include license url

**Comment by kitchenprinzessin3880** [comment]
@NTaherifar I have updated the schema, fyi.

**Comment by NTaherifar** [comment]
@kitchenprinzessin3880, Regarding the issue with the license , I've found that we need to adopt a different approach. We should define our licenses using a JSON file that contains a list of licenses. This file can either be stored in our project directory or made accessible via a URL.
I've added a licenses.json file to our shared directory, which is now available for both the sample and data repositories. In our schema, there's no need to define license_url. Instead, we just need to include a field named license_id to manage the licenses. 
I created a new issue  to implement local license in CKAN #117

**Comment by kitchenprinzessin3880** [comment]
Citation of a data file has been formatted well

<img width="774" alt="Screenshot 2024-04-17 at 1 32 59 PM" src="https://github.com/AuScope/ckan-docker/assets/11935313/0c32b5e4-711c-4a04-bb48-719135db85aa">

**Comment by kitchenprinzessin3880** [comment]
@NTaherifar About the license (on the data file page), e.g. https://repository-dev.data.auscope.org.au/dataset/test-upload-004/resource/0376e02d-b459-4404-b520-6e71edab879a?inner_span=True

There are two places with 'No License Provided'. How can we fix these?
<img width="888" alt="Screenshot 2024-04-17 at 1 34 41 PM" src="https://github.com/AuScope/ckan-docker/assets/11935313/e5903625-31cf-4a81-85f4-755eefb7b78b">

**Comment by NTaherifar** [comment]
@kitchenprinzessin3880 , The reason the license field is empty is that it was previously filled using an old format, and now the stored value in the database is not compatible with the new format. For existing datasets, you need to modify them by simply selecting the license and updating the dataset. Then, the field will be updated and the license will be displayed correctly. Just a reminder, when the license is selected correctly, it will appear only in the left panel and will no longer be visible in the additional information section

**Comment by kitchenprinzessin3880** [comment]
@NTaherifar thanks for the explanation. let me try with new dataset

**Comment by kitchenprinzessin3880** [comment]
Logged in as ckan_admin, checked the file of a newly created record. license information renders correctly
