### ISSUE TITLE
Editor Role Access

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [AuScope/ckan-docker#51]
Test instance - auscope-data-dev.geoanalytics.group

The following implementations in our repository need to be checked as they are incomplete or caused exceptions (see BOLD text):

**ROLE - EDITOR**
1. Can log in as an editor - PASS
2. Private data

- Can Add New Data (PASS)
- Can Edit Metadata - own record (PASS), Other records in AuScope org (PASS)
- Can Edit Data Files - own record (PASS), Other records in AuScope org  PASS
- Can Delete - own record (PASS), Other records in AuScope org (PASS)
- Can publish - PASS

3. Public data

- Can Add - PASS
- Can Edit Metadata YES, Can Edit Data Files - PASS
- Can delete data - PASS
- Can delete whole record - PASS

**Comment by stuartwoodman** [comment]
Will re-test this before beginning, I think at least a few of these issues have addressed.

**Comment by kitchenprinzessin3880** [comment]
Retested after @vjf fixed the DOI - all working as intended
