### ISSUE TITLE
Member (Depositor) Role Access

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [AuScope/ckan-docker#52]
Test instance - auscope-data-dev.geoanalytics.group

The following implementations in our repository need to be checked as they are incomplete or caused exceptions (see BOLD text):

**ROLE - MEMBER (DEPOSITOR)**
1. Can log in as a member - PASS
2. Private data

- Can Add New Data (PASS)
- Can Edit Metadata - own record (PASS), Cannot edit other records in AuScope org (<del>FAIL</del>) --> ASD: PASS
- Can Edit Data Files - own record (<del>FAIL, When I click on the file, I receive an error, see figure 1 below</del> PASS ), Cannot edit other records in AuScope org (PASS)
- Can Delete - own record (PASS), Cannot delete other records in AuScope org (PASS)
- Cannot publish the dataset (change from private to public) - PASS

- Cannot edit a published dataset (**FAIL**) - When I edit the already published dataset, the form automatically sets the visibility to private. When I save the form, I get the message below (fig 2). **so if they dataset is already published a member cannot delete or edit it.**

<img width="1076" alt="Screenshot 2024-03-08 at 2 45 41 pm" src="https://github.com/AuScope/ckan-docker/assets/11935313/0274dbb7-2f3b-4d9d-be77-4eefe1623d4e">

<img width="810" alt="Screenshot 2024-03-08 at 2 47 54 pm" src="https://github.com/AuScope/ckan-docker/assets/11935313/d7a1b887-be92-42eb-a4db-b955456834c6">

**Comment by kitchenprinzessin3880** [comment]
@stuartwoodman 
The following causes an internal server error
Click on an existing resource > click Remove > upload new file and the click Update Resource

**Comment by stuartwoodman** [comment]
>     2. Any published dataset cannot be edited ( we need define the scope of this e.g. what kinds of changes permitted when we allow changes to published data); currently when i edit a published data, it goes back to private mode

Yep, I picked up on this a while ago. I'm not sure we ever resolved it? I think at the time you wanted to discuss how DOI minting works with Vincent and how that would affect things.

**Comment by kitchenprinzessin3880** [comment]
Hi Stuart,
thanks for fixing it. I will test the repo this afternoon

**Comment by kitchenprinzessin3880** [comment]
@stuartwoodman 
issue 1 (internal server error when replacing files) - file can be replaced w/o error, but as a member, i cant find the delete button now when the data is private (see below)

![Screenshot 2024-03-20 at 2 45 45 PM](https://github.com/AuScope/ckan-docker/assets/11935313/92e5617a-cfb4-4e4b-acfd-ac8f6ec6bfa2)

issue 2 (member cannot update files (resources of published data)) - as a member, I created a record (https://repository-dev.data.auscope.org.au/dataset/resources/soil-gas-for-mineral-exploration-field-locations). I login as an admin, change it from private to public. I log in again as a member, and I can edit the metadata (as expected), when I click on resources > Manage > I can still see the Remove and Update Resource buttons (they are not functioning though as we agreed before). is there a way we can let users know that published data cannot be edited e.g. by hiding/changing the colour of these buttons to inactive colour.

**Comment by stuartwoodman** [comment]
> is there a way we can let users know that published data cannot be edited e.g. by hiding/changing the colour of these buttons to inactive colour.

I think that would be a UI thing. When the auth fails for a very specific reason (e.g. member is trying to delete a resource of a published dataset) I raise an exception that says exactly that, but the template just displays "Unauthorized to delete package" (or similar. So I think the template is responsible for a lot of this, and unfortunately the auth call doesn't happen until the user requests an operation (such as a delete), so the template doesn't know about it yet. We could probably add a few helper functions (I think the user_role one is there already) that the templates could use to disable some buttons or add some help text, Neda would know more about how easy that would be to do.

**Comment by kitchenprinzessin3880** [comment]
a member cannot edit published data anymore, thanks!
