### ISSUE TITLE
Zip preview 

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [AuScope/ckan-docker#55]
Tested instance - https://auscope-data-dev.geoanalytics.group
Duplicate views of the same file, see below
<img width="1377" alt="Screenshot 2024-03-06 at 6 43 30 pm" src="https://github.com/AuScope/ckan-docker/assets/11935313/407ca2fe-807c-4864-b7ac-95c36b056caa">

**Comment by stuartwoodman** [comment]
This is a strange one. Looking at file names it looks like this was using a Mac? Could be related to accessing Mac drives from Windows. From this [thread](https://discussions.apple.com/thread/4947897?sortBy=best):

>     Dot files are invisible files that OS X uses to display positions of files and folders icon for instance when you open a folder.
> 
> That is indeed what a .DS_Store file does, but that's not the ones Bogies is referring to.
> 
> 
> There are various other items that start with a period, such as .Trashes. Every drive gets a trash folder, just as Windows does to each of its drives. While it hides its own trash folders from view, Windows doesn't recognize OS X's version of the trash folder, so you see it.
> 
> 
> But you're likely talking about these. Every file you copy from OS X to a DOS/Windows formatted drive gets a ._ file. The Mac OS has a twin file system; the data fork, and the resource fork. Windows has only a data fork.
> 
> 
> In order for OS X to maintain the resource fork data on a Windows drive, it has to write the resource data as a separate data fork file. So a file named foo.tif will also get a ._foo.tif file on the drive. Mac users don't see them since UNIX automatically hides anything that starts with a period. When you copy the file back to OS X, the data and resource fork info is combined again into a normal Mac file.
> 
> 
> Most of the time, removing these are no big deal. They hold simple data like Type and Creator codes, modification dates, icons, etc. Others, like Mac Type 1 PostScript or Mac legacy TrueType fonts have all of the font data in the resource fork. Delete the ._ files for those types of fonts, and you're left with nothing.
