### ISSUE TITLE
Automate the config deployment

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [AuScope/ckan-docker#57]
Please automate the deployment of the generation of the config file (currently being done through your python script)

**Comment by bmotevalli** [comment]
We have now an automated solution to sync secrets and configs directly from vault. Two cron-jobs are deployed in our ckan namespaces in the cluster (for DEV and PROD, respectively). EVERY 20 mins a job is triggered which checks the current state of the ConfigMaps and Secrets with what is stored in Vault. If there is any difference, it will update them and restarts the pod.

In addition a mini fastapi app is deployed in each of these namespaces as well. At present, the APIs are not served on a public internet. Though, you can access them via port forwarding. The service names are: kube-fastapi-service. If you want to apply the changes immediately, you can use this API to manually enforce the updates.
