### ISSUE TITLE
Include different dates in the data submission

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [AuScope/ckan-docker#62]
- Deposit Date- The date the record was deposited into the repository (this is not the same as the metadata creation date). Data deposit should be populated when the depositor submit the record; Hidden in the submission form (visible on the metadata page)
- Publication Date - The date the data was published with a DOI through the repository; Hidden in the submission form
- Embargo Date - A limited period after which your data will be publicly available (visible on the metadata page)
- Validation needed - if the data is under embargo, the Embargo date should be later than today.

Remarks (as of 21.03.2024): we use the deposit date to generate the data citation. the data we should use in the citation is the date published

**Comment by stuartwoodman** [comment]
For deposit date we'll need to override after_create:
https://docs.ckan.org/en/2.9/extensions/plugin-interfaces.html#ckan.plugins.interfaces.IPackageController
Or possibly after_update if we're looking at when dataset is published vs first submitted.

**Comment by kitchenprinzessin3880** [comment]
Tested dataset - https://repository-dev.data.auscope.org.au/dataset/edit/kimba-airborne-electromagnetic-aem-survey
Deposit date is visible on the metadata page
<img width="1289" alt="Screenshot 2024-05-10 at 3 21 49 PM" src="https://github.com/AuScope/ckan-docker/assets/11935313/b47ad66e-ff72-4fe4-b174-bd36ef41135c">

Changed the dataset from private to public
Both the deposit date and publication date are visible on the metadata page
<img width="1367" alt="Screenshot 2024-05-10 at 3 23 14 PM" src="https://github.com/AuScope/ckan-docker/assets/11935313/fac5b6fa-36ef-43ce-b4ff-a2982bf705f0">

Embargo validation has been implemented
<img width="785" alt="Screenshot 2024-05-10 at 3 23 57 PM" src="https://github.com/AuScope/ckan-docker/assets/11935313/d42e9bb9-a010-4614-9fd4-f5268b59c513">
