### ISSUE TITLE
Prod release dependencies on domain admin access, certificate, etc.

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [AuScope/ckan-docker#67]
Steps:

- Acquire admin access to *.data.auscope.au (dependency to Rebecca and Vince)
- AWS (EASI) Certificate for the domain
    - Geoff set ups the cert and provides record_name and record_value (Geoff)
    - Vince/Alex create a DNS record for validation (Vince/Alex)
    - Create additional records for LoadBalancer (Vince/Alex and Ben)
- Set up ingress with the new certificate (Ben)
- AAF (Ben)
     - DEV: instantly becomes available
     - PROD: last time it took more than a week

**Comment by kitchenprinzessin3880** [comment]
@bmotevalli can we close this issue?

**Comment by bmotevalli** [comment]
@kitchenprinzessin3880. Not yet Anu. It is almost done. The last piece is the AAF for PROD. I am waiting for approval from AAF. Last time it took 10 days until they approved. I'll just attach the Latest Update that I put in Teams here:

Latest Update:
- All apps are deployed on the new four URLs (ingresses updated)
- AAF (DEV): is set
- AAF (PROD): **request is sent for approval. As temp solution, a test AAF is also created for PROD urls until we’ll have the approvals**.
- Vault env vars are updated and synced with cluster.

**Comment by kitchenprinzessin3880** [comment]
Thanks for the updates Ben (once you receive a confirmation from AAF on prod service, please close the issue with relevant comments).

**Comment by kitchenprinzessin3880** [comment]
@bmotevalli can you please check if repository.data.auscope.org.au uses the prod DOI too?

**Comment by bmotevalli** [comment]
AAF has approved. ENV vars are updated accordingly. Tested and works fine.
