### ISSUE TITLE
Document the flow of adding collaborators

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [AuScope/ckan-docker#68]
The repository should provide a way to share a dataset (private) with selected users e.g. journal reviewers to see a dataset that goes with a publication before the paper and the dataset is officially released.
CKAN collaborator seems to support this function (https://docs.ckan.org/en/2.9/maintaining/authorization.html#dataset-collaborators); this should be enabled Q2 (Apr-June) 2024.
@stuartwoodman FYI

**Comment by stuartwoodman** [comment]
We can add this, but given we're forcing an organization on users and have overwritten how auth/permissions work I'm not sure what affect that may have had on the collaboration functionality. Will need to look into it.

**Comment by stuartwoodman** [comment]
From the docs:

```
By default, only Administrators of the organization a dataset belongs to can add collaborators to a dataset. When adding them, they can choose between two roles: member and editor.

A member can:

    View the dataset if it is private.

An editor can do everything a member can plus:

    Make the dataset public or private.
    Edit or delete the dataset (including assigning it to an organization)
```

So only admins can add a collaborator, so the member who created the dataset would have to request it.
And we'd likely want to limit them to member role as editors can view/edit all datasets.

**Comment by kitchenprinzessin3880** [comment]
@stuartwoodman what is the status of this task? what is the process of granting access to data to the journal article reviewer

**Comment by stuartwoodman** [comment]
> @stuartwoodman what is the status of this task? what is the process of granting access to data to the journal article reviewer

On it. As always, one clever hack I put in to solve a problem ends up biting us in the... CKAN later. Should be solvable, just requires re-writing some auth and schema code. That's to get it back to the default state of having org admins add collaborators (member would have to request this), if we want users to be able to do this it will take longer.

**Comment by kitchenprinzessin3880** [comment]
we need to inform users about the process about adding collaborators

**Comment by kitchenprinzessin3880** [comment]
Action: Anu to document the process above in the manual

**Comment by kitchenprinzessin3880** [comment]
I am going to close this issue as this should be part of main guide for repository manager (https://github.com/AuScope/ckan-docker/issues/182)
