### ISSUE TITLE
Include Data submission conditions/declaration in the submission form

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [AuScope/ckan-docker#81]
Depositors should acknowledge and accept the terms of use before submitting the record. This document should be developed in consultation with AuScope data leadership.

**Comment by kitchenprinzessin3880** [comment]
working document - https://csiroau.sharepoint.com/:w:/r/sites/AuScopePortalRefresh/Shared%20Documents/General/auscope_data_repository/publications/SubmissionConditions.docx?d=w61cee3551a9f4fb490f0fc3bdfae0c9e&csf=1&web=1&e=qql2ud

**Comment by stuartwoodman** [comment]
This should be straight forward, we can just have an extra checkbox field that says the user agrees and contains a link to the T&Cs. We display it in the form_snippet and hide it in the display.

**Comment by kitchenprinzessin3880** [comment]
great..the draft is ready, just waiting for rebecca/jens to approve it

**Comment by kitchenprinzessin3880** [comment]
The UI should look like below:

Please acknowledge you have read the Data Deposit Declaration. We will respond to all questions as soon as possible, whenever possible. If you have questions or feedback, you can reach us at 
[help@data.auscope.org.au](mailto:help@data.auscope.org.au)

**Comment by kitchenprinzessin3880** [comment]
tested: DEV repo
The declaration has been added, see https://repository-dev.data.auscope.org.au/declaration
and included in the submission form
<img width="944" alt="Screenshot 2024-06-14 at 12 01 39 PM" src="https://github.com/AuScope/ckan-docker/assets/11935313/4cd63d9d-9b40-4756-8d7a-395a511a74cc">
