### ISSUE TITLE
The records published via the repository should be findable through the ARDC Research Data Australia (RDA)

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [AuScope/ckan-docker#83]
two ways
1. use ckan extension iso
2. use pycsw
Vincent to compare both ways and implement the harvesting in milestone 3

**Comment by kitchenprinzessin3880** [comment]
Test instance of AuScope geonetwork - https://augeonetwork-dev.geoanalytics.group/geonetwork

**Comment by vjf** [comment]
We had a couple of issues:

1. Older version of 'requests' library caused truncation of data sent to Geonetwork, possibly related to https://github.com/psf/requests/issues/6439
2. Older records left over from previous iterations causing the 'iso19115' plugin to create errors

**Comment by kitchenprinzessin3880** [comment]
Issues found and resolved:

1. RDA wasn't able to harvest the record from the AuScope network as the [existing record](https://auportal.geoanalytics.group/geonetwork/srv/eng/catalog.search#/metadata/79c5f1f365596693dc136c9729c3ea4de57ab5ff) contact coordinates value is in decimal (not real number). Anu has fixed the values of the record manually via the geonetwork (dev and prod).
2. the records inserted from the repository into AuScope Geonetwork do not have the category 'Dataset'. This should be added
3. for the records exported from the data repository, the landing page url included in the iso XML is incorrect e.g. `<gco:CharacterString>https://sample.data.auscope.org.au</gco:CharacterString>`
4. The harvester at https://researchdata.ardc.edu.au/registry/ is set with 'manual publication'. Anu has disabled it on the production registry- this means the records harvested by RDA will be automatically published at RDA portal.

**Comment by kitchenprinzessin3880** [comment]
@vjf https://demo.researchdata.ardc.edu.au harvestign records from prod geonetwork. i have updated it to dev geonetwork
