### ISSUE TITLE
Contact Form - Recaptha

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [AuScope/ckan-docker#85]
Place holder - Recaptcha check implemented and working
will be implemented Q2 2024

**Comment by kitchenprinzessin3880** [comment]
<img width="1020" alt="Screenshot 2024-05-23 at 11 39 09 AM" src="https://github.com/AuScope/ckan-docker/assets/11935313/2332e5ee-0cc1-40ea-9645-4da5a8330b1f">

@vjf i am getting recapcha error

**Comment by kitchenprinzessin3880** [comment]
from @vjf : For some reason Google Recaptcha stopped working in our repository projects because its project had become inaccessible (Project deleted? Keys disowned? Who knows??)

I have created a new Recaptcha in the 'geoanalytics-tooling' project and it is working again in repo-dev (see below).

Pavel, please let me know if this isn't the best place for it.

I'll push the new keys out to the other repos soon.

@PavelGolodoniuc - Can you please response here?

**Comment by PavelGolodoniuc** [comment]
@vjf, as I mentioned at the meeting, it appears to be linked with us and IM&T rotating API keys on GCP projects that might be been potentially exposed during the recent security incident. Recreating the keys is the way to go.
