### ISSUE TITLE
Minimised button is white and very difficult to see

### ISSUE THREAD

**Issue by vjf** [AuScope/ckan-docker#86]
Another tiny thing to fix later on.

When the screen is made to be quite narrow the search bar, help, about become minimised and replaced by an almost invisible index button. The index button should be a dark violet colour, not white
 
 
![image](https://github.com/AuScope/ckan-docker/assets/9968557/e2521fd7-a549-4d4a-9dba-154a0bc6aa08)

**Comment by kitchenprinzessin3880** [comment]
fixed, see below
![Uploading Screenshot 2024-04-17 at 1.21.19 PM.png…]()
