### ISSUE TITLE
Spatial Represenation - Multiple Points and Poligons

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [AuScope/ckan-docker#88]
Modify the submission form so that a data repository can include one or more points or bounding boxes.

**Comment by NTaherifar** [comment]
Refactored database schema to replace point-latitude, point-longitude, and bounding-box fields with a single location-data field using GeoJSON, simplifying spatial data management and enabling the storage of various geometries. Do you agree with this update?

**Comment by kitchenprinzessin3880** [comment]
@NTaherifar the multiple bounding boxes act strangely

1. I click on the Spatial & Temporal Tab > Area on Map
2. Draw a bounding box (this creates multiple rows, see figure 1 below)
3. I delete the bounding box and then add multiple bounding boxes, then the rows are generated correctly (figure 2)
4
<img width="1101" alt="Screenshot 2024-04-17 at 1 16 54 PM" src="https://github.com/AuScope/ckan-docker/assets/11935313/317033ed-3764-446a-a5ef-c3d2847667eb">
<img width="971" alt="Screenshot 2024-04-17 at 1 17 10 PM" src="https://github.com/AuScope/ckan-docker/assets/11935313/7ad073ff-a5c8-4b7d-9249-1a6526fc02ad">

**Comment by NTaherifar** [comment]
@kitchenprinzessin3880, It looks like the bounding box was duplicated, with two boxes having the same coordinates. When you delete the first one and add new ones, the rows then appear correctly. I've tried several times but couldn't replicate this issue. Can you please tell exactly how it happened? This will help me figure out the cause of the duplication.

**Comment by kitchenprinzessin3880** [comment]
@NTaherifar the error above disappeared, but now we have another error; see below (the icons on the map are empty)
tested - pository-dev.data.auscope.org.au/
<img width="174" alt="Screenshot 2024-05-10 at 3 08 01 PM" src="https://github.com/AuScope/ckan-docker/assets/11935313/c31c5b22-66ce-4a8f-bd49-0ae22cc56985">

**Comment by kitchenprinzessin3880** [comment]
Tested the point rendering with an existing and new dataset - the issue of duplicate lat/long has been resolved
<img width="1272" alt="Screenshot 2024-05-29 at 11 58 42 AM" src="https://github.com/AuScope/ckan-docker/assets/11935313/c5782380-5dd1-46e0-b991-1a0440d57348">
![Uploading Screenshot 2024-05-29 at 11.57.29 AM.png…]()
![Uploading Screenshot 2024-05-29 at 11.56.47 AM.png…]()

**Comment by kitchenprinzessin3880** [comment]
@NTaherifar can you please add some description on what led to the issue of duplicate lat/long before and how did you fix it here? This will be useful for future reference.
please close the issue once you add the description.

**Comment by NTaherifar** [comment]
Changes made to fix duplicate instances of markers or rectangles :

Avoid Multiple Event Listeners:
Added this.map.off before this.map.on to ensure that existing event listeners are removed before adding new ones. This prevents multiple instances of event listeners from being attached, which can cause duplicate actions.

Consistency in Event Handling:
Ensured that the event handling for L.Draw.Event.CREATED, L.Draw.Event.DELETED, and L.Draw.Event.EDITED is consistent and properly managed.
